// PCF 계산 로직에 맞는 예시 데이터
// 규칙: 하위 Tier의 PCF 미산정 시 상위 Tier PCF 계산 불가

export const PROJECT_1_DATA = {
  // Project 1: 모든 Tier PCF 계산 완료
  id: 'project-1',
  projectCode: 'SCN-2026-01',
  projectName: 'BMW iX5 배터리 공급',
  productName: '배터리 모듈 A',
  version: 'v1.0',
  customer: 'BMW',
  period: '2026-Q1',
  supplyChainVersions: ['SC-1.2', 'SC-1.1', 'SC-1.0'],
  supplyChain: {
    id: 'tier0-p1',
    tier: 'Tier 0',
    companyName: '삼성SDI',
    companyNameEn: 'Samsung SDI',
    country: 'South Korea',
    companyType: 'Operator',
    deliveryVolume: 50000,
    rawMaterialInput: 30000,
    productType: '배터리 모듈',
    emissionSource: 'Internal DB v3.2',
    pcfResult: 32420.3,  // PCF 계산 완료
    emissionIntensity: 0.6484,
    dataSubmissionStatus: 'submitted',
    verificationStatus: 'verified',
    riskLevel: 'low',
    dataInputStatus: 'completed',
    pcfCalculationStatus: 'verified',
    submissionStatus: 'verified',
    lastUpdate: '2026-03-01',
    children: [
      {
        id: 'tier1-p1-1',
        tier: 'Tier 1',
        companyName: '한국배터리',
        companyNameEn: 'Korea Battery Co.',
        country: 'South Korea',
        companyType: 'Supplier',
        deliveryVolume: 30000,
        rawMaterialInput: 20000,
        productType: '배터리 셀',
        emissionSource: 'ecoinvent 3.8',
        pcfResult: 18770.1,  // PCF 계산 완료
        emissionIntensity: 0.6257,
        dataSubmissionStatus: 'submitted',
        verificationStatus: 'verified',
        riskLevel: 'low',
        dataInputStatus: 'completed',
        pcfCalculationStatus: 'verified',
        submissionStatus: 'verified',
        lastUpdate: '2026-02-28',
        children: [
          {
            id: 'tier2-p1-1',
            tier: 'Tier 2',
            companyName: '양극재',
            companyNameEn: 'Cathode Materials Co.',
            country: 'South Korea',
            companyType: 'Supplier',
            deliveryVolume: 15000,
            rawMaterialInput: 10000,
            productType: '양극재',
            emissionSource: 'K-ETS DB',
            pcfResult: 8650.5,  // PCF 계산 완료
            emissionIntensity: 0.5767,
            dataSubmissionStatus: 'submitted',
            verificationStatus: 'verified',
            riskLevel: 'low',
            dataInputStatus: 'completed',
            pcfCalculationStatus: 'verified',
            submissionStatus: 'verified',
            lastUpdate: '2026-02-25',
            children: [
              {
                id: 'tier3-p1-1',
                tier: 'Tier 3',
                companyName: '리튬광산',
                companyNameEn: 'Lithium Mine Corp.',
                country: 'Australia',
                companyType: 'Supplier',
                deliveryVolume: 8000,
                rawMaterialInput: 5000,
                productType: '리튬 원광',
                emissionSource: 'IEA Database',
                pcfResult: 4200.8,  // PCF 계산 완료
                emissionIntensity: 0.5251,
                dataSubmissionStatus: 'submitted',
                verificationStatus: 'verified',
                riskLevel: 'low',
                dataInputStatus: 'completed',
                pcfCalculationStatus: 'verified',
                submissionStatus: 'verified',
                lastUpdate: '2026-02-20',
              },
            ],
          },
        ],
      },
      {
        id: 'tier1-p1-2',
        tier: 'Tier 1',
        companyName: '글로벌 소재',
        companyNameEn: 'Global Materials Ltd.',
        country: 'Germany',
        companyType: 'Supplier',
        deliveryVolume: 20000,
        rawMaterialInput: 10000,
        productType: '친환경 소재',
        emissionSource: 'EcoInvent DB',
        pcfResult: 6050.2,  // PCF 계산 완료 (하위 없음)
        emissionIntensity: 0.3025,
        dataSubmissionStatus: 'submitted',
        verificationStatus: 'verified',
        riskLevel: 'low',
        dataInputStatus: 'completed',
        pcfCalculationStatus: 'verified',
        submissionStatus: 'verified',
        lastUpdate: '2026-02-27',
      },
    ],
  },
};

export const PROJECT_2_DATA = {
  // Project 2: Tier 2 미제출 → Tier 1 하위 데이터 부족 → Tier 0 하위 데이터 부족
  id: 'project-2',
  projectCode: 'SCN-2026-02',
  projectName: 'Mercedes EQS 차세대 배터리',
  productName: '전고체 셀',
  version: 'v2.1',
  customer: 'Mercedes-Benz',
  period: '2026-Q2',
  supplyChainVersions: ['SC-2.1'],
  supplyChain: {
    id: 'tier0-p2',
    tier: 'Tier 0',
    companyName: '삼성SDI',
    companyNameEn: 'Samsung SDI',
    country: 'South Korea',
    companyType: 'Operator',
    deliveryVolume: 40000,
    rawMaterialInput: 25000,
    productType: '전고체 배터리',
    emissionSource: 'Internal DB v3.3',
    pcfResult: null,  // 하위 데이터 부족으로 PCF 계산 불가
    emissionIntensity: null,
    dataSubmissionStatus: 'submitted',
    verificationStatus: 'verified',
    riskLevel: 'low',
    dataInputStatus: 'completed',
    pcfCalculationStatus: 'verified',
    submissionStatus: 'verified',
    lastUpdate: '2026-03-02',
    children: [
      {
        id: 'tier1-p2-1',
        tier: 'Tier 1',
        companyName: '파워셀 테크놀로지',
        companyNameEn: 'PowerCell Technologies',
        country: 'Japan',
        companyType: 'Supplier',
        deliveryVolume: 20000,
        rawMaterialInput: 15000,
        productType: '전력 셀',
        emissionSource: 'JIS Standards',
        pcfResult: null,  // Tier 2 미제출로 PCF 계산 불가
        emissionIntensity: null,
        dataSubmissionStatus: 'submitted',
        verificationStatus: 'verified',
        riskLevel: 'medium',
        dataInputStatus: 'completed',
        pcfCalculationStatus: 'verified',
        submissionStatus: 'verified',
        lastUpdate: '2026-03-01',
        children: [
          {
            id: 'tier2-p2-1',
            tier: 'Tier 2',
            companyName: '음극재',
            companyNameEn: 'Anode Materials Inc.',
            country: 'South Korea',
            companyType: 'Supplier',
            deliveryVolume: 10000,
            rawMaterialInput: 5000,
            productType: '음극재',
            emissionSource: 'K-ETS DB',
            pcfResult: null,  // 데이터 미제출
            emissionIntensity: null,
            dataSubmissionStatus: 'not-submitted',  // 미제출
            verificationStatus: 'not-verified',
            riskLevel: 'low',
            dataInputStatus: 'pending',
            pcfCalculationStatus: 'pending',
            submissionStatus: 'pending',
            lastUpdate: '2026-02-20',
          },
        ],
      },
      {
        id: 'tier1-p2-2',
        tier: 'Tier 1',
        companyName: '스마트 컨트롤 시스템',
        companyNameEn: 'Smart Control Systems',
        country: 'Taiwan',
        companyType: 'Supplier',
        deliveryVolume: 20000,
        rawMaterialInput: 10000,
        productType: '제어 시스템',
        emissionSource: 'Taiwan LCI',
        pcfResult: 5620.3,  // PCF 계산 완료 (하위 없음)
        emissionIntensity: 0.2810,
        dataSubmissionStatus: 'submitted',
        verificationStatus: 'verified',
        riskLevel: 'low',
        dataInputStatus: 'completed',
        pcfCalculationStatus: 'verified',
        submissionStatus: 'verified',
        lastUpdate: '2026-02-27',
      },
    ],
  },
};

export const PROJECT_3_DATA = {
  // Project 3: 데이터 제출됐으나 PCF 계산 대기 중
  id: 'project-3',
  projectCode: 'SCN-2026-03',
  projectName: 'Audi Q6 e-tron ESS',
  productName: 'ESS 팩',
  version: 'v1.3',
  customer: 'Audi',
  period: '2026-Q1',
  supplyChainVersions: ['SC-3.1'],
  supplyChain: {
    id: 'tier0-p3',
    tier: 'Tier 0',
    companyName: '삼성SDI',
    companyNameEn: 'Samsung SDI',
    country: 'South Korea',
    companyType: 'Operator',
    deliveryVolume: 30000,
    rawMaterialInput: 20000,
    productType: 'ESS 모듈',
    emissionSource: 'Internal DB v3.2',
    pcfResult: null,  // 하위 Tier 1 계산 대기로 인해 계산 불가
    emissionIntensity: null,
    dataSubmissionStatus: 'submitted',
    verificationStatus: 'not-verified',
    riskLevel: 'low',
    dataInputStatus: 'completed',
    pcfCalculationStatus: 'submitted',
    submissionStatus: 'submitted',
    lastUpdate: '2026-02-29',
    children: [
      {
        id: 'tier1-p3-1',
        tier: 'Tier 1',
        companyName: '에코 패키징',
        companyNameEn: 'Eco Packaging Corp.',
        country: 'USA',
        companyType: 'Supplier',
        deliveryVolume: 15000,
        rawMaterialInput: 8000,
        productType: '포장재',
        emissionSource: 'EPA Database',
        pcfResult: 3950.3,  // PCF 계산 완료
        emissionIntensity: 0.2633,
        dataSubmissionStatus: 'submitted',
        verificationStatus: 'verified',
        riskLevel: 'low',
        dataInputStatus: 'completed',
        pcfCalculationStatus: 'verified',
        submissionStatus: 'verified',
        lastUpdate: '2026-02-28',
      },
      {
        id: 'tier1-p3-2',
        tier: 'Tier 1',
        companyName: '한국배터리',
        companyNameEn: 'Korea Battery Co.',
        country: 'South Korea',
        companyType: 'Supplier',
        deliveryVolume: 15000,
        rawMaterialInput: 12000,
        productType: '배터리 셀',
        emissionSource: 'ecoinvent 3.8',
        pcfResult: null,  // 데이터 제출됐으나 계산 대기 중
        emissionIntensity: null,
        dataSubmissionStatus: 'submitted',
        verificationStatus: 'not-verified',
        riskLevel: 'low',
        dataInputStatus: 'completed',
        pcfCalculationStatus: 'submitted',
        submissionStatus: 'submitted',
        lastUpdate: '2026-02-27',
        children: [
          {
            id: 'tier2-p3-1',
            tier: 'Tier 2',
            companyName: 'BMS 솔루션즈',
            companyNameEn: 'BMS Solutions Inc.',
            country: 'Taiwan',
            companyType: 'Supplier',
            deliveryVolume: 8000,
            rawMaterialInput: 5000,
            productType: 'BMS 모듈',
            emissionSource: 'GHG Protocol',
            pcfResult: 4120.5,  // PCF 계산 완료
            emissionIntensity: 0.5151,
            dataSubmissionStatus: 'submitted',
            verificationStatus: 'verified',
            riskLevel: 'low',
            dataInputStatus: 'completed',
            pcfCalculationStatus: 'verified',
            submissionStatus: 'verified',
            lastUpdate: '2026-02-25',
          },
        ],
      },
    ],
  },
};
